### PR TITLE
Fix longstanding bug in replace

### PR DESCRIPTION
**Pull request by telemachus**
For several years, replace has not worked in normal mode. This commit
fixes that bug. In addition, I've updated the tests and README a bit.

At this point, all existing tests are passing. There's a clean slate for
new changes or CI.

(The bug was added in #19. In the end, the fix was trivial, but it took
me too long to see it. I'd like to set up CI now, so I'll start in on that
branch after this is merged. I'd also like to update the test files to be
more sandboxed from the user's larger vim environment.)

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
I just setup Vader in CI twice in the last two days, if you like I can probably whip it out easily while it's fresh in my mind.

**Comment by alerque** [comment]
c.f. https://github.com/junegunn/vader.vim/issues/224

**Comment by telemachus** [comment]
> I just setup Vader in CI twice in the last two days, if you like I can probably whip it out easily while it's fresh in my mind.

That would be terrific! If it's okay with you, I may add/remove/rework
the tests after that, but I'm not familiar with GitHub's CI at all. If you
do the initial setup, I'll study that to learn more about CI here. Then,
I should be able to help more with that going forward.

(Btw, I don't seem to be authorized to merge the pull request. Please
go ahead and do that if it looks good to you. Thanks!)

**Comment by telemachus** [comment]
> Can you try again? I just fiddled with permissions, it may not have been setup right. It would be nice to get that straightened out.

Yes, I can now merge (and I have). Thanks.

**Comment by telemachus** [comment]
In the future, I should probably handle the merge commit better.
I apologize: I'm not used to dealing with merges through GitHub
as opposed to the command line.

**Comment by alerque** [comment]
For the record, some tests were failing until I merged this work into my CI branch, now they all pass. So you did something right ;-)

**Pull request merged**
