### PR TITLE
Fix running in the sandbox

### LINKED ISSUE #17: scriptencoding utf-8 not allowed in sandbox
When starting vim with the file which activates ``call textobj#quote#init`` (actually, neovim from git (commit neovim/neovim@e46534b42 ) I get this error:
```
Error detected while processing \
    /home/matej/.vim/pack/minpac/start/vim-textobj-quote/autoload/textobj/quote.vim:                                                                      
line    9:                                                                                 
E48: Not allowed in sandbox: scriptencoding utf-8
```
I don't know if it matters, we could use ``"\u02a4"`` instead of switching ``scriptencoding``.

After that something is wrong, e.g., ``:w`` says ``E13: File exists (add ! to override) ``, I have to run ``:w!`` to save the file.

### PR DESCRIPTION
**Pull request by mcepl**
This is a very much work in progress trying to fix #17 . I tried to fix all error messages, but it doesn't seem like working (I cannot even define new functions in the sandbox), so some other approach probably needs to be taken. Why we are in the sandbox at all?

### CODE REVIEW

**Comment by mcepl** [comment]
OK, so when I remove ``scriptencoding``, I hit another problem. When running ``'0`` (not when I open the document from the command line; and for the record using neovim from git neovim/neovim@e46534b42 ), I hit another error:
```
Error detected while processing /home/matej/.vim/pack/minpac/start/vim-textobj-quote/autoload/textobj/quote.vim:
line   14:
E48: Not allowed in sandbox: function! s:unicode_enabled()
```

**Review by alerque — COMMENTED** [review]
I've had a look at this (and even resolved the merge conflicts so it can be tested in CI) but I'm not sure I see the point. I am unable to replicate the issue this is supposed to solve. Given that the OP also is unable to replicate and has closed the original issue, would this actually help anyone? I see some potential downsides to *not* just using UTF8.

**Comment by mcepl** [comment]
No objection.

**Comment by telemachus** [comment]
I was going to suggest the same thing.

**Comment by alerque** [comment]
@mcepl Thanks for *trying* to figure this out and contribute. If this surfaces again we'll gladly revisit.

**Pull request closed without merging**
